print('Hello, World!')
print("welcome to the world of Python programming!")
print('This is a simple Python script.')
print('This script prints multiple lines of text.')
print('Each print statement outputs a line to the console.')
print('Python is a versatile language.')
print('You can use it for web development, data analysis, and more.')
print('Let\'s explore more features of Python.')
print('This is the end of the script.')
print('Thank you for running this script!')
print('Goodbye!')
print('This is a continuation of the script.')
print('We can add more functionality here.')
print('For example, we can define functions.')
print('Functions can help organize code better.')
print('This is a simple function example.')
def greet(name):
    print(f'Hello, {name}!')
greet('Xavier')
